"""
blueprints/billing.py
Stripe subscriptions, plan upgrades, webhook handling.
"""
import stripe
from datetime import datetime
from flask import (Blueprint, render_template, request, redirect,
                           url_for, flash, current_app, g, jsonify)
from flask_login import login_required, current_user
from extensions import db
from models import School, Subscription
from utils import admin_required

billing = Blueprint("billing", __name__, url_prefix="/billing")


def get_stripe():
        stripe.api_key = current_app.config["STRIPE_SECRET_KEY"]
            return stripe


        # ── Plans page ────────────────────────────────────────────────────
        @billing.route("/plans")
        @login_required
        def plans():
                school  = g.school
                    prices  = current_app.config["STRIPE_PRICES"]
                        limits  = current_app.config["PLAN_LIMITS"]
                            features= current_app.config["PLAN_FEATURES"]
                                pk      = current_app.config["STRIPE_PUBLISHABLE_KEY"]
                                    return render_template("billing/plans.html",
                                                                       school=school, prices=prices,
                                                                                                  limits=limits, features=features,
                                                                                                                             stripe_pk=pk)


                                    # ── Create Stripe Checkout Session ───────────────────────────────
                                    @billing.route("/checkout/<plan>/<cycle>", methods=["POST"])
                                    @login_required
                                    @admin_required
                                    def checkout(plan, cycle):
                                            s      = get_stripe()
                                                school = g.school
                                                    prices = current_app.config["STRIPE_PRICES"]

                                                        if plan not in prices or cycle not in ("monthly", "yearly"):
                                                                    flash("Invalid plan selected.", "danger")
                                                                            return redirect(url_for("billing.plans"))

                                                                            price_id = prices[plan][cycle]
                                                                                if not price_id:
                                                                                            flash("Stripe price not configured. Please contact support.", "danger")
                                                                                                    return redirect(url_for("billing.plans"))

                                                                                                    # Create or retrieve Stripe customer
                                                                                                        if not school.stripe_customer_id:
                                                                                                                    customer = s.Customer.create(
                                                                                                                                        email=school.email,
                                                                                                                                                    name=school.name,
                                                                                                                                                                metadata={"school_id": school.id, "subdomain": school.subdomain},
                                                                                                                                                                        )
                                                                                                                            school.stripe_customer_id = customer.id
                                                                                                                                    db.session.commit()

                                                                                                                                        proto = current_app.config["APP_PROTOCOL"]
                                                                                                                                            base  = current_app.config["BASE_DOMAIN"]
                                                                                                                                                base_url = f"{proto}://{school.subdomain}.{base}"

                                                                                                                                                    session = s.checkout.Session.create(
                                                                                                                                                                    customer=school.stripe_customer_id,
                                                                                                                                                                            payment_method_types=["card"],
                                                                                                                                                                                    line_items=[{"price": price_id, "quantity": 1}],
                                                                                                                                                                                            mode="subscription",
                                                                                                                                                                                                    success_url=f"{base_url}/billing/success?session_id={{CHECKOUT_SESSION_ID}}",
                                                                                                                                                                                                            cancel_url=f"{base_url}/billing/plans",
                                                                                                                                                                                                                    metadata={"school_id": school.id, "plan": plan, "cycle": cycle},
                                                                                                                                                                                                                        )
                                                                                                                                                        return redirect(session.url, code=303)


                                                                                                                                                    # ── Checkout Success ──────────────────────────────────────────────
                                                                                                                                                    @billing.route("/success")
                                                                                                                                                    @login_required
                                                                                                                                                    def success():
                                                                                                                                                            session_id = request.args.get("session_id")
                                                                                                                                                                flash("Subscription activated! Welcome to your new plan.", "success")
                                                                                                                                                                    return render_template("billing/success.html", session_id=session_id)


                                                                                                                                                                # ── Subscription Expired ──────────────────────────────────────────
                                                                                                                                                                @billing.route("/expired")
                                                                                                                                                                def expired():
                                                                                                                                                                        school = g.school
                                                                                                                                                                            return render_template("billing/expired.html", school=school)


                                                                                                                                                                        # ── Cancel Subscription ───────────────────────────────────────────
                                                                                                                                                                        @billing.route("/cancel", methods=["POST"])
                                                                                                                                                                        @login_required
                                                                                                                                                                        @admin_required
                                                                                                                                                                        def cancel():
                                                                                                                                                                                s      = get_stripe()
                                                                                                                                                                                    school = g.school

                                                                                                                                                                                        if not school.stripe_subscription_id:
                                                                                                                                                                                                    flash("No active subscription found.", "warning")
                                                                                                                                                                                                            return redirect(url_for("billing.plans"))

                                                                                                                                                                                                            s.Subscription.modify(
                                                                                                                                                                                                                            school.stripe_subscription_id,
                                                                                                                                                                                                                                    cancel_at_period_end=True,
                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                flash("Your subscription will cancel at the end of the current billing period.", "info")
                                                                                                                                                                                                                    return redirect(url_for("billing.plans"))


                                                                                                                                                                                                                # ── Stripe Webhook ────────────────────────────────────────────────
                                                                                                                                                                                                                @billing.route("/webhook", methods=["POST"])
                                                                                                                                                                                                                def webhook():
                                                                                                                                                                                                                        payload    = request.data
                                                                                                                                                                                                                            sig_header = request.headers.get("Stripe-Signature")
                                                                                                                                                                                                                                secret     = current_app.config["STRIPE_WEBHOOK_SECRET"]

                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                event = stripe.Webhook.construct_event(payload, sig_header, secret)
                                                                                                                                                                                                                                                    except (ValueError, stripe.error.SignatureVerificationError):
                                                                                                                                                                                                                                                                return jsonify({"error": "Invalid signature"}), 400

                                                                                                                                                                                                                                                                _handle_webhook_event(event)
                                                                                                                                                                                                                                                                    return jsonify({"status": "ok"}), 200


                                                                                                                                                                                                                                                                def _handle_webhook_event(event):
                                                                                                                                                                                                                                                                        """Update school subscription state from Stripe events."""
                                                                                                                                                                                                                                                                            data   = event["data"]["object"]
                                                                                                                                                                                                                                                                                etype  = event["type"]

                                                                                                                                                                                                                                                                                    # ── checkout.session.completed ────────────────────────────────
                                                                                                                                                                                                                                                                                        if etype == "checkout.session.completed":
                                                                                                                                                                                                                                                                                                    meta  = data.get("metadata", {})
                                                                                                                                                                                                                                                                                                            sid   = meta.get("school_id")
                                                                                                                                                                                                                                                                                                                    plan  = meta.get("plan", "starter")
                                                                                                                                                                                                                                                                                                                            cycle = meta.get("cycle", "monthly")
                                                                                                                                                                                                                                                                                                                                    school = School.query.get(sid)
                                                                                                                                                                                                                                                                                                                                            if school:
                                                                                                                                                                                                                                                                                                                                                            school.plan                   = plan
                                                                                                                                                                                                                                                                                                                                                                        school.billing_cycle          = cycle
                                                                                                                                                                                                                                                                                                                                                                                    school.stripe_subscription_id = data.get("subscription")
                                                                                                                                                                                                                                                                                                                                                                                                db.session.commit()

                                                                                                                                                                                                                                                                                                                                                                                                    # ── invoice.payment_succeeded ─────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                        elif etype == "invoice.payment_succeeded":
                                                                                                                                                                                                                                                                                                                                                                                                                    sub_id = data.get("subscription")
                                                                                                                                                                                                                                                                                                                                                                                                                            school = School.query.filter_by(stripe_subscription_id=sub_id).first()
                                                                                                                                                                                                                                                                                                                                                                                                                                    if school:
                                                                                                                                                                                                                                                                                                                                                                                                                                                    period_end = data.get("lines", {}).get("data", [{}])[0].get("period", {}).get("end")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if period_end:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    school.subscription_ends_at = datetime.utcfromtimestamp(period_end)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Log subscription record
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sub_record = Subscription(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    school_id=school.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    stripe_subscription_id=sub_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    stripe_invoice_id=data.get("id"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    plan=school.plan,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    billing_cycle=school.billing_cycle,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    amount=data.get("amount_paid", 0) / 100,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status="active",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    period_end=school.subscription_ends_at,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        db.session.add(sub_record)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    db.session.commit()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # ── invoice.payment_failed ────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif etype == "invoice.payment_failed":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sub_id = data.get("subscription")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                school = School.query.filter_by(stripe_subscription_id=sub_id).first()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if school:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Subscription(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                school_id=school.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                stripe_subscription_id=sub_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                plan=school.plan,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                status="past_due",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    db.session.commit()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # ── customer.subscription.deleted ────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif etype == "customer.subscription.deleted":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sub_id = data.get("id")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                school = School.query.filter_by(stripe_subscription_id=sub_id).first()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if school:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        school.plan                   = "free"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    school.stripe_subscription_id = None
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                db.session.commit()
